"""create shares table

Revision ID: 866acb0b2997
Revises: 076ad1a59939
Create Date: 2026-06-03 19:26:12.074990

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '866acb0b2997'
down_revision: Union[str, None] = '076ad1a59939'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shares',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('file_id', sa.String(length=36), nullable=True),
    sa.Column('folder_id', sa.String(length=36), nullable=True),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('uses', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shares_file_id'), 'shares', ['file_id'], unique=False)
    op.create_index(op.f('ix_shares_folder_id'), 'shares', ['folder_id'], unique=False)
    op.create_index(op.f('ix_shares_owner_id'), 'shares', ['owner_id'], unique=False)
    op.create_index(op.f('ix_shares_token'), 'shares', ['token'], unique=True)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shares_token'), table_name='shares')
    op.drop_index(op.f('ix_shares_owner_id'), table_name='shares')
    op.drop_index(op.f('ix_shares_folder_id'), table_name='shares')
    op.drop_index(op.f('ix_shares_file_id'), table_name='shares')
    op.drop_table('shares')
    # ### end Alembic commands ###
