"""initial empty migration

Revision ID: 8f4961064091
Revises: 
Create Date: 2026-06-03 16:30:18.283612

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '8f4961064091'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
