"""create files table

Revision ID: 9b4a7e659aef
Revises: ea06c9d07fde
Create Date: 2026-06-03 19:22:24.632255

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '9b4a7e659aef'
down_revision: Union[str, None] = 'ea06c9d07fde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=1024), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('s3_key', sa.String(length=2048), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('s3_key')
    )
    op.create_index(op.f('ix_files_owner_id'), 'files', ['owner_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_files_owner_id'), table_name='files')
    op.drop_table('files')
    # ### end Alembic commands ###
